{{- if .Values.clyde.containerdMirrorAdd }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "clyde.fullname" . }}-cleanup
  namespace: {{ include "clyde.namespace" . }}
  labels:
    app.kubernetes.io/component: cleanup
    {{- include "clyde.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "post-delete"
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
    helm.sh/hook-weight: "0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: cleanup
      {{- include "clyde.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cleanup
        {{- include "clyde.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      priorityClassName: {{ .Values.priorityClassName }}
      containers:
      - name: cleanup
        image: "{{ include "clyde.image" . }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - cleanup
          - --containerd-registry-config-path={{ .Values.clyde.containerdRegistryConfigPath }}
          - --addr=:{{ .Values.service.cleanup.port }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: readiness
        ports:
          - name: readiness
            containerPort: {{ .Values.service.cleanup.port }}
            protocol: TCP
        volumeMounts:
          - name: containerd-config
            mountPath: {{ .Values.clyde.containerdRegistryConfigPath }}
      volumes:
        - name: containerd-config
          hostPath:
            path: {{ .Values.clyde.containerdRegistryConfigPath }}
            type: DirectoryOrCreate
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clyde.fullname" . }}-cleanup
  namespace: {{ include "clyde.namespace" . }}
  labels:
    app.kubernetes.io/component: cleanup
    {{- include "clyde.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "post-delete"
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
    helm.sh/hook-weight: "0"
spec:
  selector:
    app.kubernetes.io/component: cleanup
    {{- include "clyde.selectorLabels" . | nindent 4 }}
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: readiness
      port: {{ .Values.service.cleanup.port }}
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "clyde.fullname" . }}-cleanup-wait
  namespace: {{ include "clyde.namespace" . }}
  labels:
    app.kubernetes.io/component: cleanup-wait
    {{- include "clyde.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "post-delete"
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
    helm.sh/hook-weight: "1"
spec:
  containers:
    - name: cleanup-wait
      image: "{{ include "clyde.image" . }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      args:
        - cleanup-wait
        - --probe-endpoint={{ include "clyde.fullname" . }}-cleanup.{{ include "clyde.namespace" . }}.svc.{{ .Values.clusterDomain }}:{{ .Values.service.cleanup.port }}
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
{{- end }}
