apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clyde.serviceAccountName" . }}
  namespace: {{ include "clyde.namespace" . }}
  labels:
    {{- include "clyde.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
