{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "clyde.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace | default (include "clyde.namespace" .) }}
  labels:
    {{- include "clyde.labels" . | nindent 4 }}
    {{- if .Values.serviceMonitor.labels -}}
    {{ toYaml .Values.serviceMonitor.labels | nindent 4}}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ include "clyde.namespace" . }}   # points to the namespace where your Service runs
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      {{- include "clyde.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
      {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
