apiVersion: v1
kind: Service
metadata:
  name: {{ include "clyde.fullname" . }}
  namespace: {{ include "clyde.namespace" . }}
  labels:
    app.kubernetes.io/component: metrics
    {{- include "clyde.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "clyde.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clyde.fullname" . }}-registry
  namespace: {{ include "clyde.namespace" . }}
  labels:
    {{- include "clyde.labels" . | nindent 4 }}
  {{- if .Values.service.registry.topologyAwareHintsEnabled }}
  annotations:
    service.kubernetes.io/topology-mode: "auto"
  {{- end }}
spec:
  type: NodePort
  selector:
    {{- include "clyde.selectorLabels" . | nindent 4 }}
  ports:
    - name: registry
      port: {{ .Values.service.registry.port }}
      targetPort: registry
      nodePort: {{ .Values.service.registry.nodePort }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clyde.fullname" . }}-bootstrap
  namespace: {{ include "clyde.namespace" . }}
  labels:
    {{- include "clyde.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "clyde.selectorLabels" . | nindent 4 }}
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: router
      port: {{ .Values.service.router.port }}
      protocol: TCP
